### PR TITLE
update noobaa APIS and images

### PR DESCRIPTION
**Pull request by iamniting**
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

### CODE REVIEW

**Review by Nikhil-Ladha — APPROVED** [review]
/lgtm

**Review by Nikhil-Ladha — COMMENTED** [review]
/lgtm
/unhold

**Review by malayparida2000 — APPROVED** [review]
/unhold

**Review by malayparida2000 — APPROVED** [review]
/lgtm

**Pull request merged**
