### PR TITLE
Remove clusterresourcequota metrics

### PR DESCRIPTION
**Pull request by synarete**
Exporting clusterresourcequota via OCS is duplication of metrics which are already exported by OpenShift. Removed.

Refs BZ-2016513

### CODE REVIEW

**Comment by umangachapagain** [comment]
Removing metrics is fine. But, do we also want to remove alerts? Wouldn't it be better to use existing metrics to generate this alert for OCS specific clusterresourcequotas?

**Comment by synarete** [comment]
> 

@umangachapagain  This is a very good question: should we create alert rules for something which is no longer part of OCS metrics. @jarrpa What is your opinion?

**Review by jarrpa — APPROVED** [review]
For the moment I'll say no. If someone is actually impacted by this we can always add them back.

/lgtm

**Pull request merged**
