### PR TITLE
Support specifying Node Affinity for CephToolbox pod

### PR DESCRIPTION
**Pull request by malayparida2000**
This will allow the CephToolbox pod to get scheduled on specific node.

https://bugzilla.redhat.com/show_bug.cgi?id=2249640

### CODE REVIEW

**Review by iamniting — APPROVED** [review]

**Comment by malayparida2000** [comment]
We are again seeing the noobaa error where noobaa used to stay struck in configuring phase forever

```
~ $ oc get noobaa
NAME     S3-ENDPOINTS                    STS-ENDPOINTS                   IMAGE                                        PHASE         AGE
noobaa   ["https://10.0.80.130:31195"]   ["https://10.0.80.130:32707"]   quay.io/noobaa/noobaa-core:master-20240108   Configuring   4m59s
```

**Pull request merged**
