### PR TITLE
ensure interal cluster is only allowed in the OperatorNamespace 

### PR DESCRIPTION
**Pull request by iamniting**
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

### CODE REVIEW

**Review by umangachapagain — CHANGES_REQUESTED** [review]
This restriction does not make sense. Why can't I have external mode in OperatorNamespace and internal mode in another namespace?

**Comment by iamniting** [comment]
> This restriction does not make sense. Why can't I have external mode in OperatorNamespace and internal mode in another namespace?

You can still have external in the operator namespace. We are just blocking internal in other namespaces just to be safe if someone creates it, as it is out of our support matrix.

**Comment by umangachapagain** [comment]
> > This restriction does not make sense. Why can't I have external mode in OperatorNamespace and internal mode in another namespace?
> 
> You can still have external in the operator namespace. We are just blocking internal in other namespaces just to be safe if someone creates it, as it is out of our support matrix.
>
I'd prefer not to block it, but better be safe I guess.

Can you please squash all commits? It's all part of same logical change.

**Comment by iamniting** [comment]
> > > This restriction does not make sense. Why can't I have external mode in OperatorNamespace and internal mode in another namespace?
> > 
> > 
> > You can still have external in the operator namespace. We are just blocking internal in other namespaces just to be safe if someone creates it, as it is out of our support matrix.
> 
> I'd prefer not to block it, but better be safe I guess.
> 
> Can you please squash all commits? It's all part of same logical change.

done

**Review by umangachapagain — APPROVED** [review]

**Pull request merged**
