### PR TITLE
Bug 2248449: Fusion HCI integration changes for OCS operator [4.14 Backport]

### PR DESCRIPTION
**Pull request by nb-ohad**
This PR contains backports of multiple fixes and enhancements to allow integration of the OCS Operator with Fusion HCI deployment and management model

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
@malayparida2000 @iamniting pls check if this failure can be ignored or not

**Comment by iamniting** [comment]
> @malayparida2000 @iamniting pls check if this failure can be ignored or not

Storagecluster was not ready in the earlier one, Let's see if it can come online now.

**Comment by malayparida2000** [comment]
> > @malayparida2000 @iamniting pls check if this failure can be ignored or not
> 
> Storagecluster was not ready in the earlier one, Let's see if it can come online now.

This could have been due to the ceph image issue https://github.com/rook/rook/issues/13136.
I have merged the fix https://github.com/red-hat-storage/ocs-operator/pull/2277 on 4.14 too just now, We will rerun this again. And I am unable to access the CI environment as it will give access only to the person who raises the PR.

**Pull request merged**
