### PR TITLE
add topology mode annotation rgw service

### PR DESCRIPTION
**Pull request by thotz**
add topology mode annotation rgw for service

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
/lgtm

**Review by iamniting — CHANGES_REQUESTED** [review]
Can you pls remove the BZ number from the title, If you want you can add the link to the BZ in the description

**Comment by malayparida2000** [comment]
@iamniting All tests have passed, PTAL.

@thotz please give devel_ack + in the BZ & also ask for QE ack from QE

**Review by iamniting — APPROVED** [review]

**Pull request merged**
