### PR TITLE
Rename StorageClassRequest api to StorageRequest

### PR DESCRIPTION
**Pull request by rohan47**
Rename StorageClassRequest api to StorageRequest

### CODE REVIEW

**Comment by rohan47** [comment]
Todo:
- Fix generated changes
- Fix unit tests
- Test the changes

**Comment by nb-ohad** [comment]
@rohan47 This PR is very hard to review, you replaced a lot of files instead of renaming them so it is hard to understand the actual changes. Can you please make it so that renamed files will be recognized as renames so we could understand what the diff is?

**Comment by rohan47** [comment]
Testing is pending

**Review by leelavg — COMMENTED** [review]
all looks good, I don't see change in rbac for provider-server, could you pls recheck?

**Comment by leelavg** [comment]
> all looks good, I don't see change in rbac for provider-server, could you pls recheck?
- this file https://github.com/red-hat-storage/ocs-operator/blob/main/rbac/provider-role.yaml, let me know if it's already included, thanks.

**Comment by leelavg** [comment]
/ok-to-test

pls rebase.

**Comment by leelavg** [comment]
@nb-ohad I've deployed this PR manually and could verify the feature, pls override the CI and merge, thanks!

```
# k get storagerequest
NAME                                              STORAGETYPE        PHASE
storagerequest-1da6affb08ec64b8c15b4336a4535b98   sharedfilesystem   Ready
storagerequest-4188d8886677cf944955ab9e327a4cce   blockpool          Ready

# k get po -ndefault -lpart-of=test
NAME                  READY   STATUS    RESTARTS   AGE
app-block-1           1/1     Running   0          54s
app-block-clone-1     1/1     Running   0          52s
app-block-restore-1   1/1     Running   0          53s
app-file-1            1/1     Running   0          52s
app-file-clone-1      1/1     Running   0          51s
app-file-restore-1    1/1     Running   0          51s

root@forge ~/.../ocs-operator [pr2550 𝓧] > 
# k get pvc -ndefault -lpart-of=test
NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                  AGE
ceph-block-1           Bound    pvc-8803eb1e-6477-43b8-9b8d-dcce670f730e   100Mi      RWO            ocs-storagecluster-ceph-rbd   64s
ceph-block-clone-1     Bound    pvc-4a3746ff-e8fd-4b75-aa94-6b675ecd155c   100Mi      RWO            ocs-storagecluster-ceph-rbd   63s
ceph-block-restore-1   Bound    pvc-0631e805-93b3-4fb1-b802-4a3b85675861   100Mi      RWO            ocs-storagecluster-ceph-rbd   63s
ceph-file-1            Bound    pvc-f02f3b52-f796-44a1-8091-4a09abf8a300   100Mi      RWO            ocs-storagecluster-cephfs     62s
ceph-file-clone-1      Bound    pvc-8ad48121-a171-4b76-a1e0-e107450dfc13   100Mi      RWO            ocs-storagecluster-cephfs     61s
ceph-file-restore-1    Bound    pvc-22fe70d9-ad74-4a8e-9789-48669bc1c1a7   100Mi      RWO            ocs-storagecluster-cephfs     62s

root@forge ~/.../ocs-operator [pr2550 𝓧] > 
# k get vs -ndefault -lpart-of=test
NAME                READYTOUSE   SOURCEPVC      SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS                 SNAPSHOTCONTENT                                    CREATIONTIME   AGE
ceph-block-snap-1   true         ceph-block-1                           100Mi         ocs-storagecluster-ceph-rbd   snapcontent-7648693d-e9a0-4b6a-81b6-b9aa2a67093c   71s            71s
ceph-file-snap-1    true         ceph-file-1                            100Mi         ocs-storagecluster-cephfs     snapcontent-119a5e09-cb94-46e0-821d-6f1b231e3b67   70s            70s
```

**Comment by leelavg** [comment]
@iamniting could you pls approve this, it seems Ohad only override the CI and missed approving it yesterday, as mentioned in above comments I've manually tested it and CI also passed once. thanks.

**Review by iamniting — APPROVED** [review]

**Pull request merged**
