### PR TITLE
bundle: add readOnlyRootFilesystem for ocs-operator

### PR DESCRIPTION
**Pull request by iamniting**
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2273387

### CODE REVIEW

**Review by Nikhil-Ladha — APPROVED** [review]
lgtm

**Review by Nikhil-Ladha — APPROVED** [review]
lgtm

**Comment by leelavg** [comment]
LG as per my testing
```
# ko get csv | grep ocs
ocs-client-operator.v4.16.0-70.custom-root       OpenShift Data Foundation Client   4.16.0-70.custom-root              Succeeded
ocs-operator.v4.16.0-70.custom-root              OpenShift Container Storage        4.16.0-70.custom-root              Succeeded

# ko get deploy ocs-operator -oyaml | rg -A5 -i securitycontext
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
--
      securityContext:
        runAsNonRoot: true
      serviceAccount: ocs-operator
      serviceAccountName: ocs-operator
      terminationGracePeriodSeconds: 10
      tolerations:


# ko get deploy ocs-operator -oyaml | grep -P -A5 'volumeMounts:|volumes:'
        volumeMounts:
        - mountPath: /etc/private-key
          name: onboarding-private-key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
--
      volumes:
      - name: onboarding-private-key
        secret:
          defaultMode: 420
          optional: true
          secretName: onboarding-private-key

# ko get secret onboarding-private-key
Error from server (NotFound): secrets "onboarding-private-key" not found

# ko exec -it deploy/ocs-operator -- ls -lR /etc/private-key
/etc/private-key:
total 0

# ko create secret generic --from-literal=key=value onboarding-private-key
secret/onboarding-private-key created

# within a minute
# ko exec -it deploy/ocs-operator -- ls -lR /etc/private-key
/etc/private-key:
total 0
lrwxrwxrwx. 1 root 1000690000 10 Apr  8 14:33 key -> ..data/key
 
# ko exec -it deploy/ocs-operator -- cat /etc/private-key/key
value

# ko exec -it deploy/ocs-operator -- touch /etc/dummy
touch: cannot touch '/etc/dummy': Read-only file system
command terminated with exit code 1
```

shouldn't the same treatment be given to pods that are reconciled by the controllers, ie, provider-server & onboarding job?

**Comment by iamniting** [comment]
> LG as per my testing
> 
> ```
> # ko get csv | grep ocs
> ocs-client-operator.v4.16.0-70.custom-root       OpenShift Data Foundation Client   4.16.0-70.custom-root              Succeeded
> ocs-operator.v4.16.0-70.custom-root              OpenShift Container Storage        4.16.0-70.custom-root              Succeeded
> 
> # ko get deploy ocs-operator -oyaml | rg -A5 -i securitycontext
>         securityContext:
>           allowPrivilegeEscalation: false
>           capabilities:
>             drop:
>             - all
>           readOnlyRootFilesystem: true
> --
>       securityContext:
>         runAsNonRoot: true
>       serviceAccount: ocs-operator
>       serviceAccountName: ocs-operator
>       terminationGracePeriodSeconds: 10
>       tolerations:
> 
> 
> # ko get deploy ocs-operator -oyaml | grep -P -A5 'volumeMounts:|volumes:'
>         volumeMounts:
>         - mountPath: /etc/private-key
>           name: onboarding-private-key
>       dnsPolicy: ClusterFirst
>       restartPolicy: Always
>       schedulerName: default-scheduler
> --
>       volumes:
>       - name: onboarding-private-key
>         secret:
>           defaultMode: 420
>           optional: true
>           secretName: onboarding-private-key
> 
> # ko get secret onboarding-private-key
> Error from server (NotFound): secrets "onboarding-private-key" not found
> 
> # ko exec -it deploy/ocs-operator -- ls -lR /etc/private-key
> /etc/private-key:
> total 0
> 
> # ko create secret generic --from-literal=key=value onboarding-private-key
> secret/onboarding-private-key created
> 
> # within a minute
> # ko exec -it deploy/ocs-operator -- ls -lR /etc/private-key
> /etc/private-key:
> total 0
> lrwxrwxrwx. 1 root 1000690000 10 Apr  8 14:33 key -> ..data/key
>  
> # ko exec -it deploy/ocs-operator -- cat /etc/private-key/key
> value
> 
> # ko exec -it deploy/ocs-operator -- touch /etc/dummy
> touch: cannot touch '/etc/dummy': Read-only file system
> command terminated with exit code 1
> ```
> 
> shouldn't the same treatment be given to pods that are reconciled by the controllers, ie, provider-server & onboarding job?

I added the permissions to the provider-server as well. But did not added for the jobs.

**Pull request merged**
