### PR TITLE
Bug 2154164:[release-4.11] disable rook webhook

### PR DESCRIPTION
**Pull request by subhamkrai**
disable rook webhook untill we supporte it officially.

Signed-off-by: subhamkrai <srai@redhat.com>

### CODE REVIEW

**Comment by iamniting** [comment]
I would prefer to use cherry-pick robot here

**Comment by subhamkrai** [comment]
@iamniting PTAL

**Comment by subhamkrai** [comment]
the errors doesn't seems to be coming from my pr

**Review by iamniting — APPROVED** [review]

**Comment by iamniting** [comment]
> the errors doesn't seems to be coming from my pr

It will be merged soon

**Pull request merged**
