### PR TITLE
Bug 2119516:[release-4.7]expose option to force remove the OSD in osd

### PR DESCRIPTION
**Pull request by subhamkrai**
adding option to expose `--force-osd-removal` `<true/false>`.
It will help when Ceph indicates the OSD is not safe-to-destroy.

Signed-off-by: subhamkrai <srai@redhat.com>

### CODE REVIEW

**Comment by subhamkrai** [comment]
cc @iamniting

**Review by travisn — CHANGES_REQUESTED** [review]
@subhamkrai Are the changes other than reconcile.go intended to be pulled with this PR? It looks unrelated

**Comment by subhamkrai** [comment]
> @subhamkrai Are the changes other than reconcile.go intended to be pulled with this PR? It looks unrelated

yes, before that the CI was failing, so I @iamniting came up with that commits.

**Pull request merged**
