### PR TITLE
Mark enableCrushUpdates as true for all the pools created

### PR DESCRIPTION
**Pull request by malayparida2000**
With recent changes in rook, without this flag rook operator would not
be able to update crush rules by default. This was giving rise
to the issue again where the mgr logs would complain about
"won't scale due to overlapping roots" & pool's PG won't scale beyond 1.

### CODE REVIEW

**Review by travisn — COMMENTED** [review]
LGTM that all the data and metadata pools, and .mgr pool are updated. Can we verify in a test cluster they are all covered? Just to confirm we don't need a follow-up PR.

**Comment by malayparida2000** [comment]
Testing

With the fix image created a fresh cluster, wrote around 9.5GB data each to the rbd pool & fs pool. Can see the PG nums scaling up.

```
sh-5.1$ ceph df
--- RAW STORAGE ---
CLASS   SIZE    AVAIL    USED  RAW USED  %RAW USED
ssd    6 TiB  5.9 TiB  57 GiB    57 GiB       0.93
TOTAL  6 TiB  5.9 TiB  57 GiB    57 GiB       0.93
 
--- POOLS ---
POOL                                        ID  PGS   STORED  OBJECTS     USED  %USED  MAX AVAIL
ocs-storagecluster-cephblockpool             1   64  9.5 GiB    2.56k   28 GiB   0.55    1.7 TiB
.mgr                                         2    1  577 KiB        2  1.7 MiB      0    1.7 TiB
ocs-storagecluster-cephfilesystem-metadata   3   16  834 KiB       24  2.5 MiB      0    1.7 TiB
ocs-storagecluster-cephfilesystem-data0      4   32  9.4 GiB    2.41k   28 GiB   0.54    1.7 TiB
```

```
sh-5.1$ ceph osd pool ls detail
pool 1 'ocs-storagecluster-cephblockpool' replicated size 3 min_size 2 crush_rule 1 object_hash rjenkins pg_num 64 pgp_num 64 autoscale_mode on last_change 160 lfor 0/0/34 flags hashpspool,selfmanaged_snaps stripe_width 0 target_size_ratio 0.49 application rbd read_balance_score 1.17
pool 2 '.mgr' replicated size 3 min_size 2 crush_rule 4 object_hash rjenkins pg_num 1 pgp_num 1 autoscale_mode on last_change 24 flags hashpspool stripe_width 0 pg_num_max 32 pg_num_min 1 application mgr read_balance_score 3.00
pool 3 'ocs-storagecluster-cephfilesystem-metadata' replicated size 3 min_size 2 crush_rule 2 object_hash rjenkins pg_num 16 pgp_num 16 autoscale_mode on last_change 68 lfor 0/0/34 flags hashpspool stripe_width 0 pg_autoscale_bias 4 pg_num_min 16 recovery_priority 5 application cephfs read_balance_score 1.31
pool 4 'ocs-storagecluster-cephfilesystem-data0' replicated size 3 min_size 2 crush_rule 5 object_hash rjenkins pg_num 32 pgp_num 32 autoscale_mode on last_change 38 lfor 0/0/36 flags hashpspool stripe_width 0 target_size_ratio 0.49 application cephfs read_balance_score 1.13
```

**Pull request merged**
