### PR TITLE
Migrate odf-info structs to API folder

### PR DESCRIPTION
**Pull request by raaizik**
## Changes

Converts odf-info structs into its own API
#2440

### CODE REVIEW

**Comment by nb-ohad** [comment]
A couple of points:
* As suggested by @umangachapagain in an offline discussion. A better name for the file containing the new type would be `odfinfo_config.go`. Mainly because the `_type` suffix is usually reserved for k8s API types.  
* This is a new API and we have no indication of its stability. It is better we have it in the v1alpha1 folder
* The second commit seems unrelated to this change and I would request to separate it into its own PR

**Comment by raaizik** [comment]
> A couple of points:
> 
>     * As suggested by @umangachapagain in an offline discussion. A better name for the file containing the new type would be `odfinfo_config.go`. Mainly because the `_type` suffix is usually reserved for k8s API types.
> 
>     * This is a new API and we have no indication of its stability. It is better we have it in the v1alpha1 folder
> 
>     * The second commit seems unrelated to this change and I would request to separate it into its own PR

Done @nb-ohad

**Pull request merged**
