### PR TITLE
storagecluster: move topology map reconciliation into its own resourceManager

### PR DESCRIPTION
**Pull request by jarrpa**
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Review by nbalacha — COMMENTED** [review]
While the code looks fine, this does seem to differ from the other entries in the resource manager which are managing k8s CR objects unlike the topologyMap.  Is that fine?
Can you add the reason for the change in the commit message?

**Comment by jarrpa** [comment]
> While the code looks fine, this does seem to differ from the other entries in the resource manager which are managing k8s CR objects unlike the topologyMap. Is that fine?
> Can you add the reason for the change in the commit message?

Fair enough, done.

**Review by obnoxxx — APPROVED** [review]
this looks good to moe

/lgtm

@nbalacha  - I think your comment has been addressed.

**Pull request merged**
