### PR TITLE
Fix KMS regression in MCG deployment

### PR DESCRIPTION
**Pull request by aruniiird**
Flag 'sc.Spec.Encryption.Enable' is deprecated and now we use
'sc.Spec.Encryption.KeyManagementService.Enable'.

Signed-off-by: Arun Kumar Mohan <amohan@redhat.com>

### CODE REVIEW

**Comment by aruniiird** [comment]
Working on the test failures...

**Comment by aruniiird** [comment]
Tests fixed... Ready for some initial reviews... Thanks

**Review by umangachapagain — APPROVED** [review]

**Pull request merged**
