### PR TITLE
Added network configuration setting for CephObjectStore

### PR DESCRIPTION
**Pull request by rohan47**
Added Network setting to enable/disable hostNetwork for CephObjectStore

### CODE REVIEW

**Comment by rohan47** [comment]
Need to test on a baremetal setup
(stuck with a faulty setup)

**Comment by rohan47** [comment]
Tested the changes

**Review by iamniting — APPROVED** [review]
/hold

@nb-ohad pls take a look

**Review by leelavg — APPROVED** [review]

**Pull request merged**
