### PR TITLE
Add unit test for storageclassclaim RPC

### PR DESCRIPTION
**Pull request by Madhu-1**
Did some code cleanup and  added unit test case for FulfillStorageClassClaim, RevokeStorageClassClaim and GetStorageClassClaimConfig RPC.

### CODE REVIEW

**Review by umangachapagain — APPROVED** [review]
/hold

**Comment by Madhu-1** [comment]
@umangachapagain rebased against the main branch PTAL

**Review by umangachapagain — APPROVED** [review]

**Pull request merged**
