### PR TITLE
Fix permissions for newly added resources

### PR DESCRIPTION
**Pull request by aruniiird**
Added permissions to list/get/watch CephRBDMirrors and StorageClasses

Signed-off-by: Arun Kumar Mohan <amohan@redhat.com>

### CODE REVIEW

**Review by umangachapagain — CHANGES_REQUESTED** [review]
You need to add RBAC to https://github.com/red-hat-storage/ocs-operator/blob/main/rbac/exporter-role.yaml file and regenerate the CSV and bundle for the complete fix.
This file is only used for manual deployments.

**Comment by aruniiird** [comment]
@umangachapagain ,
Ran, `make gen-latest-csv` and `make gen-latest-deploy-yaml` and `make ocs-metric-exporter`
Updated the commit with new files.
But I'm still not seeing an update in the `metrics/deploy/rbac.yaml` file. Let me know if I have missed any build command

**Review by umangachapagain — APPROVED** [review]
/lgtm

**Comment by aruniiird** [comment]
@umangachapagain , test `ocs-operator-ci` is failing here. Locally it passed... Let me know if anything else to be done here

```
Success: no out of source tree changes found for dependency files
Installing controller-gen@v0.9.2
Installed controller-gen@v0.9.2
Updating generated code
/home/amohan/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
Updating generated manifests
/home/amohan/go/bin/controller-gen rbac:roleName=manager-role crd:generateEmbeddedObjectMeta=true paths=./api/... webhook paths="./..." output:crd:artifacts:config=config/crd/bases
Verifying generated code and manifests
hack/verify-generated.sh
Success: no out of source tree changes found for generated files
Generating latest deployment yaml file
hack/gen-deployment-yaml.sh
Verifying deployment yaml changes
hack/verify-latest-deploy-yaml.sh
Success: no out of source tree changes found for deploy/deploy-with-olm.yaml
```

**Pull request merged**
