### PR TITLE
remove vr and vrc CRDs from owned

### PR DESCRIPTION
**Pull request by Rakshith-R**
This commit removes vr and vrc CRDs from
owned list, since CSI-Addons will now be
owning them.

Signed-off-by: Rakshith R <rar@redhat.com>

Refers: https://issues.redhat.com/browse/RHSTOR-3378

/cc @Madhu-1 @agarwal-mudit @iamniting

### CODE REVIEW

**Comment by iamniting** [comment]
Hello @Rakshith-R We are already hitting multiple problems using this approach for noobaa and looking forward to removing it. I suggest you remove it from ocs and have it in the CSI addons. There's no need to have it under the required section of CSV.

**Comment by Madhu-1** [comment]
> Hello @Rakshith-R We are already hitting multiple problems using this approach for noobaa and looking forward to removing it. I suggest you remove it from ocs and have it in the CSI addons. There's no need to have it under the required section of CSV.

If we delete it, won't there be any upgrade problems?

**Comment by Rakshith-R** [comment]
> > Hello @Rakshith-R We are already hitting multiple problems using this approach for noobaa and looking forward to removing it. I suggest you remove it from ocs and have it in the CSI addons. There's no need to have it under the required section of CSV.
>If we delete it, won't there be any upgrade problems?
I have the same concerns.

CSI-Addons does not depend on anything, I don't think there will be any dependency problems when this pr is taken
along with https://github.com/red-hat-storage/odf-operator/pull/245.
wdyt @iamniting ?

**Comment by iamniting** [comment]
> > Hello @Rakshith-R We are already hitting multiple problems using this approach for noobaa and looking forward to removing it. I suggest you remove it from ocs and have it in the CSI addons. There's no need to have it under the required section of CSV.
> 
> If we delete it, won't there be any upgrade problems?

I don't think and anyway, we will test it.

**Comment by iamniting** [comment]
> > > Hello @Rakshith-R We are already hitting multiple problems using this approach for noobaa and looking forward to removing it. I suggest you remove it from ocs and have it in the CSI addons. There's no need to have it under the required section of CSV.
> > > If we delete it, won't there be any upgrade problems?
> > > I have the same concerns.
> 
> CSI-Addons does not depend on anything, I don't think there will be any dependency problems when this pr is taken along with [red-hat-storage/odf-operator#245](https://github.com/red-hat-storage/odf-operator/pull/245). wdyt @iamniting ?

There will be problems. We have ocs-operator and csi-addons in the dependencies file. This means OLM will bring both of them Even before odf is installed. Marking some CRD's required in OCS can bring any CSI-addons version and we want a specific version only.

**Review by iamniting — APPROVED** [review]
/lgtm
/hold cancel

**Comment by iamniting** [comment]
/hold

wait for upgrade tests results

**Comment by iamniting** [comment]
/hold cancel

upgrade is passed as well

**Pull request merged**
