### PR TITLE
Bug 2235571:[release-4.13] Fix upgrade issue when storagecluster is not present

### PR DESCRIPTION
**Pull request by malayparida2000**
This is an manual backport of https://github.com/red-hat-storage/ocs-operator/pull/2165

Wait for https://github.com/red-hat-storage/ocs-operator/pull/2196 before merging

### CODE REVIEW

**Comment by b-ranto** [comment]
FYI: We have made a custom downstream build and it passed the CI for us.

**Review by b-ranto — APPROVED** [review]

**Comment by malayparida2000** [comment]
Doing manual merge as our CI uses cephv17, which is pulling the v17.2.7 automaticaly which fails the osds.
Ref-
https://bugzilla.redhat.com/show_bug.cgi?id=2247313#c3
https://github.com/rook/rook/issues/13136

**Pull request merged**
