### PR TITLE
monitoring: runbooks documentation files

### PR DESCRIPTION
**Pull request by jmolmo**
Include information about how to add the alert documentation files in runbook repo and how to link the alert and the runbook file

### CODE REVIEW

**Review by bipuladh — APPROVED** [review]

**Review by umangachapagain — APPROVED** [review]

**Comment by agarwal-mudit** [comment]
@jmolmo you need to make the csv changes.

**Comment by iamniting** [comment]
@jmolmo Can you pls rebase and push the changes again? Even I don't see an option to run it again, I think that is due to the change we made recently in the actions.

**Comment by jmolmo** [comment]
@iamniting rebased and fixed the commit sign verification.

**Pull request merged**
