### PR TITLE
update to rook v1.7.3

### PR DESCRIPTION
**Pull request by thotz**
Bumping up rook version to v1.7.3

Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>

### CODE REVIEW

**Comment by thotz** [comment]
Can anyone please check into the failure, following are mentioned in the logs : 
```
 ++ OS_TYPE=Linux
+ set +e
+ echo 'Deleting noobaa objects'
Deleting noobaa objects
+ oc -n openshift-storage delete noobaa --all
error: the server doesn't have a resource type "noobaa"
+ echo 'Deleting all storageclusters'
Deleting all storageclusters
+ oc -n openshift-storage delete storagecluster --all
error: the server doesn't have a resource type "storagecluster"
+ set -e
+ echo 'Deleting subscriptions'
Deleting subscriptions
+ oc -n openshift-storage delete subscription --all
No resources found 
 + rm -rf build/_output/cluster-deploy-manifests
Deploying ocs to cluster
hack/cluster-deploy.sh
2021-09-22 07:16:20.195071 I | Deploying ocs image quay.io/ocs-dev/ocs-registry:latest
panic: timed out waiting for the condition: waiting on deployment ocs-operator to be created
goroutine 1 [running]:
main.main()
	/go/src/github.com/red-hat-storage/ocs-operator/tools/cluster-deploy/cluster-deploy.go:46 +0x3bf
dumping debug information
ClusterVersion: Stable at "4.9.0-0.ci.test-2021-09-22-063952-ci-op-ix1dpkvy-latest"
ClusterOperators:
	All healthy and stable
ERROR: cluster-deploy failed.
make: *** [Makefile:133: cluster-deploy] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-09-22T07:35:50Z"}
error: failed to execute wrapped command: exit status 2 

ERROR: cluster-deploy failed.
make: *** [Makefile:133: cluster-deploy] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-09-22T07:35:50Z"}
error: failed to execute wrapped command: exit status 2
--- 
```

**Review by umangachapagain — CHANGES_REQUESTED** [review]
These changes are not enough.

You can refer to https://github.com/red-hat-storage/ocs-operator/pull/1141/commits for what needs to be done and how to structure commit.

**Comment by thotz** [comment]
@umangachapagain PTAL

**Review by umangachapagain — CHANGES_REQUESTED** [review]
- You also need to change version here: https://github.com/red-hat-storage/ocs-operator/blob/main/hack/common.sh#L47
- Since 1.7.7 is already available, should we move to that?
- Generated changes should be in separate commit. Vendor changes should be in separate commit.

**Comment by thotz** [comment]
>     * You also need to change version here: https://github.com/red-hat-storage/ocs-operator/blob/main/hack/common.sh#L47
Sure
> 
>     * Since 1.7.7 is already available, should we move to that?
@umangachapagain :
Yaa I understand, but I want to reduce risk as sum as possible. The change from current head to 1.7.3 is minimal IMO, hence used 1.7.3. If this goes to ocs 4.9z then IMO better to use 1.7.3 than latest one

> 
>     * Generated changes should be in separate commit. Vendor changes should be in separate commit.
Sure

**Review by umangachapagain — CHANGES_REQUESTED** [review]
YAML changes in 1st commit should be part of 2nd commit.
Script changes in 2nd commit should be part of 1st commit.

Looks good otherwise.

**Review by umangachapagain — COMMENTED** [review]
/lgtm

**Pull request merged**
