### PR TITLE
Bug 2253013:[release-4.17] Mark enableCrushUpdates as true for all the pools created

### PR DESCRIPTION
**Pull request by malayparida2000**
With recent changes in rook, without this flag rook operator would not
be able to update crush rules by default. This was giving rise
to the issue again where the mgr logs would complaint about
"won't scale due to overlapping roots" & pool's PG won't scale beyond 1.

### CODE REVIEW

**Comment by malayparida2000** [comment]
manual backport for https://github.com/red-hat-storage/ocs-operator/pull/2751

**Comment by iamniting** [comment]
Can you pls look at CI failures?

**Comment by iamniting** [comment]
@rewantsoni Do we need to backport #2670? 

If yes can we do it before this PR is merged otherwise there will be merge conflicts.

**Comment by rewantsoni** [comment]
> otherwise

Yes, on it

**Comment by iamniting** [comment]
@malayparida2000 I believe once #2755 is merged automatic cherry-pick will also work.

**Comment by malayparida2000** [comment]
> @malayparida2000 I believe once #2755 is merged automatic cherry-pick will also work.

Yes, Thanks Nitin.

**Comment by iamniting** [comment]
Will be done with #2756

**Pull request closed without merging**
