### PR TITLE
ocs-to-ocs: fix: rbac and GVK

### PR DESCRIPTION
**Pull request by subhamkrai**
ocs-to-ocs: fix rbac and  GVK

Signed-off-by: subhamkrai <srai@redhat.com>

### CODE REVIEW

**Review by Madhu-1 — APPROVED** [review]
LGTM

**Review by umangachapagain — COMMENTED** [review]
Please add some description about what each commit fixes and how.

**Review by umangachapagain — APPROVED** [review]

**Comment by Madhu-1** [comment]
@subhamkrai  we need manual backporting, not sure why cherry-pick failed.

**Comment by agarwal-mudit** [comment]
even https://github.com/red-hat-storage/ocs-operator/pull/1664 failed for a automatic backport

**Pull request merged**
