### PR TITLE
toolbox: add `tty:true` to toolbox deployment

### PR DESCRIPTION
**Pull request by subhamkrai**
adding `tty:true` to toolbox deployment
as it need to acces terminal.

Signed-off-by: subhamkrai <srai@redhat.com>

### CODE REVIEW

**Comment by subhamkrai** [comment]
^^ @leseb

**Review by leseb — CHANGES_REQUESTED** [review]
My bad, I got confused by both jobs, thanks for the follow-up. We need one commit to revert and one to add TTY to the toolbox.

**Comment by nbalacha** [comment]
Removed Privileged = false because the toolbox was unable to access the ceph-keyring.
It was decided to revert the change to get this to work and then continue to debug this.

**Review by leseb — CHANGES_REQUESTED** [review]
I don't think 54d344cec1382244dabd28a6bda2315ca99ce4cc is a revert commit, please use git revert and push again. We don't need the changes from `controllers/storagecluster/job_templates.go` either

**Comment by nbalacha** [comment]
Looks good to me but will wait for @leseb's review.

**Review by leseb — CHANGES_REQUESTED** [review]
Still, not there, we need to revert this https://github.com/red-hat-storage/ocs-operator/pull/1406/commits/bee58ad86273b5efde81e282d2a239022f13f137 properly. Then we can have a commit that add `tty` to the right place.

**Comment by subhamkrai** [comment]
> Still, not there, we need to revert this [bee58ad](https://github.com/red-hat-storage/ocs-operator/commit/bee58ad86273b5efde81e282d2a239022f13f137) properly. Then we can have a commit that adds `tty` to the right place.

Added 3 commits

1. to revert privileged commit
2. to revert the wrong file to add tty
3. added commit to add tty in wright file

**Review by leseb — CHANGES_REQUESTED** [review]
Almost there, when you revert a commit always explain why.

**Review by leseb — APPROVED** [review]

**Review by agarwal-mudit — APPROVED** [review]

**Pull request merged**
