### PR TITLE
hack: make golangci-lint.sh more verbose

### PR DESCRIPTION
**Pull request by jarrpa**
This is to help debug problems when running in the OpenShift CI, but
also should be generally useful.

Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Review by iamniting — CHANGES_REQUESTED** [review]
Instead of this curl and script method why don't we directly use `go install`

**Comment by jarrpa** [comment]
> Instead of this curl and script method why don't we directly use `go install`

Because these are the recommended instructions, after just using GH Actions, per their own documentation: https://golangci-lint.run/usage/install/ This also allows devs to run it locally without pushing to a repo first.

**Comment by iamniting** [comment]
> > Instead of this curl and script method why don't we directly use `go install`
> 
> Because these are the recommended instructions, after just using GH Actions, per their own documentation: https://golangci-lint.run/usage/install/ This also allows devs to run it locally without pushing to a repo first.

Even installing via `go install` allows the same as we are doing other installs like controller-gen etc in the makefile.

**Comment by jarrpa** [comment]
Unrelated, the CI still seems to be facing some networking issues, this time in functests.... I'll keep an eye on this and bug the DPTP team as needed.

**Review by iamniting — APPROVED** [review]
/lgtm

**Comment by jarrpa** [comment]
I added a new commit for build-functests, just to see.

**Comment by jarrpa** [comment]
Yup, problem still persists... let's keep this open and retesting until we confirm the issue has been resolved.

/hold

**Review by BlaineEXE — APPROVED** [review]

**Pull request merged**
