### PR TITLE
must-gather: add Yati as an approver for must-gather

### PR DESCRIPTION
**Pull request by agarwal-mudit**
Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
@yati1998 FYI

**Comment by yati1998** [comment]
> @yati1998 FYI
Thanks @agarwal-mudit

**Review by umangachapagain — APPROVED** [review]
🥳 🥳 🥳 🥳

**Pull request merged**
