### PR TITLE
Revert "Merge pull request #2305 from leelavg/5072-onboard"

### PR DESCRIPTION
**Pull request by leelavg**
This reverts commit 19293d06bc7d39365e3e2f4cc8b929522b2cc9d1, reversing changes made to df7a76936e982c19899222443e173511a8058c96.

ref: https://github.com/red-hat-storage/ocs-operator/pull/2305#issuecomment-1843328326

### CODE REVIEW

**Comment by leelavg** [comment]
will wait for #2308

**Comment by leelavg** [comment]
@umangachapagain @iamniting this PR was originally merged into main w/ partial reviews and from then it's hindering me to resolve conflicts as I had to raise a PR w/ 2 commits, w/ a revert and feature.

eventually this code needs to be pulled by client-operator as well and that's creating a couple more issues.

Ask:
- can this revert PR be merged to main so that client-operator can pull the main successfully w/o any changes to provider api
- then I'll be able to rebase on main w/o any conflicts, I already tried a couple of ways but those coming out to be either ugly workaround or straightway bad

On me:
- after merge to main, I'll get the changes to 4.15 as well via usual bug process

thanks

**Review by nb-ohad — APPROVED** [review]

**Pull request merged**
