### PR TITLE
Upgrade ocs metrics exporter & ocs operator to use golang 1.18 image

### PR DESCRIPTION
**Pull request by malayparida2000**
Signed-off-by: Malay Kumar Parida <mparida@redhat.com>

### CODE REVIEW

**Comment by Madhu-1** [comment]
change at https://github.com/red-hat-storage/ocs-operator/blob/main/Dockerfile#L2 required

**Comment by malayparida2000** [comment]
> change at https://github.com/red-hat-storage/ocs-operator/blob/main/Dockerfile#L2 required

Thanks Madhu for pointing this out, Have made the change

**Review by Madhu-1 — APPROVED** [review]
/lgtm

**Review by iamniting — APPROVED** [review]
/lgtm

**Pull request merged**
