### PR TITLE
Update local ceph rules' annotations

### PR DESCRIPTION
**Pull request by rexagod**
Update local ceph rule file based on the latest Ceph master.

Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>

### CODE REVIEW

**Review by umangachapagain — COMMENTED** [review]
We do not just download upstream rules and apply it downstream.

We have a separate project [ceph-mixins](https://github.com/ceph/ceph-mixins) where rules are added or https://github.com/red-hat-storage/ocs-operator/tree/main/metrics/mixin for ocs specific metrics.

The final generated YAML is a K8s object with rules that match OCS deployment. Upstream Ceph rules may not apply as it is.

**Comment by rexagod** [comment]
> Upstream Ceph rules may not apply as it is.

ACK, so does this mean that I should point https://github.com/red-hat-storage/ocs-operator/pull/1774/files#diff-ffea8b477bf82a7034c97d82ad37e9d0a6ace823b7ec27263475fbd423d48095R10 to https://raw.githubusercontent.com/ceph/ceph-mixins/master/extras/manifests/prometheus-ceph-rules.yaml?

**Comment by rexagod** [comment]
But I'm assuming someone (or something) already makes sure that the ceph-mixins alerts are replicated here. If that's the case, we don't need this PR.

**Comment by rexagod** [comment]
@umangachapagain Does the above comment sound good to you?

**Comment by rexagod** [comment]
We'd still need documentation links present here in any case, so updated the local ceph rules file with the *predicted* links.

**Review by umangachapagain — COMMENTED** [review]
Is it expected for these links to throw a 404 error?

**Comment by rexagod** [comment]
@umangachapagain Yes. These are placeholder links that will be updated by the documentation team before the GA happens in December.

**Comment by rexagod** [comment]
/cc @umangachapagain
Hello Umanga, please review, thanks.

**Comment by umangachapagain** [comment]
> /cc @umangachapagain Hello Umanga, please review, thanks.

Yeah I'm wondering if we should merge a PR that adds broken (as of now) links. Or, if we can wait until the links actually work.

**Pull request closed without merging**
