### PR TITLE
Bug 2247739: Remove StorageClientIncompatiblePlatformVersion alert

### PR DESCRIPTION
**Pull request by leelavg**
- It was found StorageClientIncompatiblePlatformVersion doesn't add any actionable insight to the end user
- To sum up, after this commit we will have 2 new ALERTs with 2 severity levels each
- StorageClientHearbeatMissed: Warn after 2 min and Critical after 5 min (no change in this commit)
- StorageClientIncompatibleOperatorVersion: Warn if client is lagging by 1 minor verison and Critical if it is ahead by 1 or lags by more than 1 minor version
- Remove metrics corresponding to the alert

### CODE REVIEW

**Comment by leelavg** [comment]
/hold

testing in progress.

**Comment by leelavg** [comment]
/unhold

verified the alert.

**Review by umangachapagain — APPROVED** [review]

**Comment by leelavg** [comment]
- all metrics wrt client for posterity

image

- one of the alert that is part of this PR corresponding to above metrics state

image

**Pull request merged**
