### PR TITLE
set FlappingRestartIntervalHours to 24 hrs

### PR DESCRIPTION
**Pull request by sp98**
when `FlappingRestartIntervalHours` interval is set, OSD pods will start as a bash script. The script will make OSD pod to sleep for 24 hrs if the OSD daemon was stopped due to flapping of the OSDs.

https://bugzilla.redhat.com/show_bug.cgi?id=2244517

### CODE REVIEW

**Comment by travisn** [comment]
@iamniting Any concerns with pulling in the latest Rook API for 4.14 with this change?

**Comment by iamniting** [comment]
> @iamniting Any concerns with pulling in the latest Rook API for 4.14 with this change?

There are no concerns about merging it in the main. I am not sure about 4.14, If we can get the acks from all parties we can merge it. otherwise, we will have to wait for 4.14.1.

**Comment by agarwal-mudit** [comment]
@iamniting @sp98 We decided to take this issue in 4.14, can we please merge it asap

**Review by iamniting — APPROVED** [review]

**Comment by iamniting** [comment]
@sp98 Can you pls manually create the PR?

**Pull request merged**
