### PR TITLE
upgrade rook api to pre-release 1.11.4

### PR DESCRIPTION
**Pull request by umangachapagain**
This is required to fix issues with Mutliclusterservice feature.

### CODE REVIEW

**Review by iamniting — APPROVED** [review]

**Review by iamniting — CHANGES_REQUESTED** [review]
Looks like we need to update the bundle.

**Comment by iamniting** [comment]
> /cherry-pick release-4.11

Is this really necessary for 4.11, or was it a typo?

**Comment by umangachapagain** [comment]
> > /cherry-pick release-4.11
> 
> Is this really necessary for 4.11, or was it a typo?
>
typo. Can't find command to cancel it. Will delete it later.

Changes are good now.

**Review by iamniting — APPROVED** [review]

**Pull request merged**
