### PR TITLE
Remove support TSC check & always use TSCs for osd placements

### PR DESCRIPTION
**Pull request by malayparida2000**
Topology Spread Constraints have been supported since kube version 1.19. It's a cleaner way of spreading osds compared to podAffinity and podAntiAffinity. So we should always use TSCs for osd placements.

### CODE REVIEW

**Comment by malayparida2000** [comment]
Original discussion is here https://github.com/red-hat-storage/ocs-operator/pull/2448#discussion_r1483420062

**Comment by parth-gr** [comment]
I hope it doesnt removes the  nodeAffinity
```
 placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: storage-profile
                  operator: Exists
                  value: class1
```

**Comment by malayparida2000** [comment]
> I hope it doesnt removes the nodeAffinity
> 
> ```
>  placement:
>       nodeAffinity:
>         requiredDuringSchedulingIgnoredDuringExecution:
>           nodeSelectorTerms:
>             - matchExpressions:
>                 - key: storage-profile
>                   operator: Exists
>                   value: class1
> ```

What is this node affinity about, I don't think we have this in ocs-op, is this something related to provider consumer mode?

**Comment by parth-gr** [comment]
> > I hope it doesnt removes the nodeAffinity
> > ```
> >  placement:
> >       nodeAffinity:
> >         requiredDuringSchedulingIgnoredDuringExecution:
> >           nodeSelectorTerms:
> >             - matchExpressions:
> >                 - key: storage-profile
> >                   operator: Exists
> >                   value: class1
> > ```
> 
> What is this node affinity about, I don't think we have this in ocs-op, is this something related to provider consumer mode?

Ohh I thought it is auto present, it is mainly to schedule osd pods based on node labels(for multiple device classes)

lgtm

**Review by iamniting — APPROVED** [review]

**Comment by leelavg** [comment]
@malayparida2000 due to this PR I'm hitting a panic at https://github.com/red-hat-storage/ocs-operator/blob/main/controllers/storagecluster/cephcluster.go#L825 when I deploy https://github.com/red-hat-storage/ocs-operator/blob/main/deploy/single-node-storagecluster-provider.yaml, maybe it is too localised to the config in that yaml however I didn't hit this in previous (<=4.16) releases.

Will take a look at a later point, dropping now not to forget.

**Pull request merged**
