### PR TITLE
Remove volume replication operator image from ocs-operator

### PR DESCRIPTION
**Pull request by malayparida2000**
Refers- [RHSTOR-3391](https://issues.redhat.com/browse/RHSTOR-3391)

Till now, volume replication is a separate entity, and Rook is owning it as part of its CSV. As we have CSI-addons, a generic library for storage-specific operation, so moving volume replication to csi-addons-kubernetes repo as a new controller.

So removing the default volume replication operator image from the scripts, then the csv merger & the ocs-operator csv.

### CODE REVIEW

**Comment by malayparida2000** [comment]
/hold

Putting a hold as the related work on csi-addons, ceph-csi & rook is not done yet.

**Comment by malayparida2000** [comment]
@Rakshith-R

**Review by Rakshith-R — COMMENTED** [review]
looks good to me, 
but we need to wait for https://github.com/rook/rook/pull/10777 to be merged and backported + DS sync

**Comment by malayparida2000** [comment]
> Pls squash first and second commit

@iamniting Done

**Review by iamniting — COMMENTED** [review]
/lgtm
/hold wait for rook PR to be merged

**Comment by agarwal-mudit** [comment]
@iamniting Which PR? I think rook PR is merged

**Comment by malayparida2000** [comment]
> @iamniting Which PR? I think rook PR is merged

Yes, It merged yesterday. Lets merge this now? @agarwal-mudit

**Review by iamniting — APPROVED** [review]
/lgtm

**Pull request merged**
