### PR TITLE
Bug 2005970: [release-4.8] add check for PodAntiAffinity not nil

### PR DESCRIPTION
**Pull request by subhamkrai**
add check for PodAntiAffinity not nil before checking
underlying resources otherwise it will cause nil pointer
err. Also updating unit test to test this nil pointer
condition.

Signed-off-by: subhamkrai <srai@redhat.com>
(cherry picked from commit 2c9b8417d729ce089dcb65ff83de741a5c8a0402)

### CODE REVIEW

**Comment by subhamkrai** [comment]
@agarwal-mudit

**Review by jarrpa — APPROVED** [review]
/lgtm

**Comment by jarrpa** [comment]
Looks like a CI infra flake.... trying again.

/test ocs-operator-bundle-e2e-aws

**Comment by jarrpa** [comment]
The bug in the e2e tests seems to be new but unrelated... I'll look into it later, for now skipping it. 

/override ci/prow/ocs-operator-bundle-e2e-aws

**Pull request merged**
