### PR TITLE
ocs-to-ocs: list within namespace

### PR DESCRIPTION
**Pull request by subhamkrai**
list storageConsumerList and node ip within namespace

Closes: https://github.com/red-hat-storage/ocs-operator/issues/1514
Signed-off-by: subhamkrai <srai@redhat.com>

### CODE REVIEW

**Comment by subhamkrai** [comment]
@nb-ohad @kesavanvt ^^^

**Review by iamniting — CHANGES_REQUESTED** [review]
Can you add permissions for the node, we do not have permissions for it as of now.

**Review by iamniting — APPROVED** [review]
/lgtm

**Pull request merged**
