### PR TITLE
Update ocs-operator version & go mod dependencies

### PR DESCRIPTION
**Pull request by malayparida2000**

### CODE REVIEW

**Comment by leelavg** [comment]
@malayparida2000 generally when'll the version.go file is updated as I still see it has 4.15

**Comment by malayparida2000** [comment]
> @malayparida2000 generally when'll the version.go file is updated as I still see it has 4.15

Oh, Sorry I missed that

**Comment by malayparida2000** [comment]
@leelavg After ocs-client operator is updated to version 4.16.0 please do update here
https://github.com/red-hat-storage/ocs-operator/blob/493179cfe22040e5e637216c4742643aefa53eea/hack/common.sh#L92
https://github.com/red-hat-storage/ocs-operator/blob/493179cfe22040e5e637216c4742643aefa53eea/catalog/index.yaml#L21

**Comment by malayparida2000** [comment]
@nik-redhat do update here after rook downstream version is updated top 4.16
https://github.com/red-hat-storage/ocs-operator/blob/493179cfe22040e5e637216c4742643aefa53eea/catalog/index.yaml#L32

**Review by iamniting — APPROVED** [review]

**Pull request merged**
