### PR TITLE
controllers: remove storageprofiles from storageclassrequest 

### PR DESCRIPTION
**Pull request by jarrpa**
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

### CODE REVIEW

**Comment by leelavg** [comment]
Do I need to also rename StorageProfile field in StorageClaims?

**Comment by jarrpa** [comment]
> Do I need to also rename/remove StorageProfile field in StorageClaims?

...I wouldn't think so? It's just a string, I'm still making use of it here: https://github.com/red-hat-storage/ocs-operator/pull/2517/files#diff-30c208b17ae3a7fc2e92dbb904d5a5489f1a6d2837ca319525b5549c61a07256R406

**Review by leelavg — APPROVED** [review]
/lgtm

**Comment by leelavg** [comment]
Although changes look good, my vote shouldn't have merged the PR 😕

**Pull request merged**
