### PR TITLE
remove CSI_DISABLE_HOLDER_PODS key for all clusters 4.18 and onwards

### PR DESCRIPTION
**Pull request by iamniting**
Customers have had two releases (4.16, 4.17) for migration, As planned we are removing this setting.

Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

### CODE REVIEW

**Comment by iamniting** [comment]
@BlaineEXE Do we have a story created in the JIRA to complete this task?

**Comment by BlaineEXE** [comment]
No, and I should verify with PM that we want to take this change for 4.17. Please don't merge this until we are certain.

Currently, all greenfield clusters will have holders disabled, which is the minimum requirement for 4.17+.

**Comment by iamniting** [comment]
> No, and I should verify with PM that we want to take this change for 4.17. Please don't merge this until we are certain.
> 
> Currently, all greenfield clusters will have holders disabled, which is the minimum requirement for 4.17+.

Pls do let me know once you have the info.

**Review by Nikhil-Ladha — APPROVED** [review]
/lgtm

**Pull request merged**
