### PR TITLE
must-gather: collect rados objects created by cephcsi

### PR DESCRIPTION
**Pull request by agarwal-mudit**

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
For https://bugzilla.redhat.com/show_bug.cgi?id=1890438

**Comment by agarwal-mudit** [comment]
Attaching output files which were gathered by running must-gather on an OCP cluster
[rados_obj_rbd.txt](https://github.com/openshift/ocs-operator/files/6816903/rados_obj_rbd.txt)
[rados_obj_cephfs.txt](https://github.com/openshift/ocs-operator/files/6816904/rados_obj_cephfs.txt)
[rados_lspools.txt](https://github.com/openshift/ocs-operator/files/6816905/rados_lspools.txt)

**Comment by Madhu-1** [comment]
Appologies for suggesting this one late

```
Instead of looping the PV object can we do it like this?

* List filesystem and Get the metadata pool name of the filesystem

$ceph fs ls
name: myfs, metadata pool: myfs-metadata, data pools: [myfs-data0 ]

* List omapkeys in csi.volumes.default in filesystem metadata pool
$ rados listomapkeys csi.volumes.default --pool=myfs-metadata --namespace=csi
csi.volume.pvc-3ff1d3b3-f80c-47d9-91a6-a056650bd595
csi.volume.pvc-fc57a7e1-ee98-47b7-9326-0a7fc81db1c7

and get the omap details of above-listed PVC object

 * List omapkeys in csi.snaps.default in filesystem metadata pool

$ rados listomapkeys csi.snaps.default --pool=myfs-metadata --namespace=csi
csi.snap.snapshot-ad90bb4d-0956-4384-b595-dc1c3c9fb6ca

and get the omap details of above-listed snapshot object
```

above can be done for rbd also.

The above will help us to list the stale omap details also.

**Pull request closed without merging**
