### PR TITLE
Update ocs-operator direct dependencies noobaa and rook

### PR DESCRIPTION
**Pull request by malayparida2000**

### CODE REVIEW

**Comment by malayparida2000** [comment]
Depends on https://github.com/operator-framework/operator-lifecycle-manager/pull/3374
to update k8s version on olm repo to solve the import issue.

**Comment by parth-gr** [comment]
A comment to track this.

**Comment by malayparida2000** [comment]
@parth-gr if your PR is being blocked I would suggest you can just update the github.com/rook/rook/pkg/apis to the latest & avoiding any other API updated. That would work & would unblock your work. Suggesting this as we have no ETA for the OLM PR mentioned above.

**Comment by iamniting** [comment]
Will be done via #2763

**Comment by iamniting** [comment]
@parth-gr Once #2763 is merged you will be unblocked.

**Comment by iamniting** [comment]
Closing this as #2763 is merged

**Pull request closed without merging**
