### PR TITLE
Upgrades: Go 1.18, Operator SDK 1.20.0, Rook v1.10.0, Ceph v17, Csiaddons v0.5.0

### PR DESCRIPTION
**Pull request by malayparida2000**
Go 1.18, K8s 1.24.3, Operator SDK 1.20.0, Controller-runtime 0.12.3, Controller-gen 0.9.2, Rook v1.10.0, Ceph v17, Csiaddons v0.5.0 

These will be the base for 4.12

### CODE REVIEW

**Comment by iamniting** [comment]
@umangachapagain We also need the API changes as well right or this should be enough?

**Comment by malayparida2000** [comment]
@iamniting , As per our latest discussion I have made the changes to go.mod & related vendor updates also.

**Review by umangachapagain — COMMENTED** [review]
Looks good.
Should we also upgrade the K8s and controller runtime version as long as it doesn't break Rook?

**Comment by malayparida2000** [comment]
> Looks good. Should we also upgrade the K8s and controller runtime version as long as it doesn't break Rook?

Had the same question, Which K8 version should we jump to? and also what about the operator SDK version?

**Review by iamniting — APPROVED** [review]
/lgtm
/hold 

@umangachapagain Pls take a look once. It looks good to me.

**Pull request merged**
