### PR TITLE
Bug 2270889: [release-4.14] Revert "add topology mode annotation rgw service"

### PR DESCRIPTION
**Pull request by sp98**
This reverts commit f5ba884b012bf0a7acfe612578f1f0091b2d1fd2.

Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>
(cherry picked from commit ef469011231b9ba925acab1457d9ea02b73039fa)

### CODE REVIEW

**Review by thotz — APPROVED** [review]

**Review by agarwal-mudit — APPROVED** [review]
/lgtm

**Pull request merged**
