### PR TITLE
refactor metrics exporter deployment

### PR DESCRIPTION
**Pull request by umangachapagain**
Refactor parts of metrics exporter deployment to simplfy code and keep it readable.
It also fixes bugs related to updating deployment artifacts.

### CODE REVIEW

**Comment by umangachapagain** [comment]
/hold
Testing the changes.

**Review by iamniting — APPROVED** [review]

**Comment by umangachapagain** [comment]
/hold
found another issue that is easier to fix in this PR.

**Review by iamniting — APPROVED** [review]

**Pull request merged**
