### PR TITLE
must-gather: skip helper pod creation and ceph log collection

### PR DESCRIPTION
**Pull request by agarwal-mudit**
skip helper pod creation and ceph log collection for MCG only cluster

Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
/hold
tested on MCG only cluster, need to test on the normal one.

**Comment by agarwal-mudit** [comment]
/hold cancel
Tested on both type of clusters, helper pod is not being created on the standalone cluster

**Comment by agarwal-mudit** [comment]
@yati1998 please review

**Review by umangachapagain — APPROVED** [review]

**Review by yati1998 — APPROVED** [review]

**Pull request merged**
