### PR TITLE
BUG 2292114: api: changed storageConsumer status fields to optional

### PR DESCRIPTION
**Pull request by rohan47**
Changed the status fields for storageconsumers to optional

### CODE REVIEW

**Comment by leelavg** [comment]
@rohan47 pls also add marker `+optional` on all these fields. I know the testing works, adding this will *not* result (can cross check as well) in a changed CRD and so further testing isn't required. 

Ref: https://github.com/kubernetes/community/blob/master/contributors%2Fdevel%2Fsig-architecture%2Fapi-conventions.md

**Comment by leelavg** [comment]
@rohan47 I looked at kubebuilder docs to see if there is an option to set the optional at struct level, seems there is one https://book.kubebuilder.io/reference/markers.html#difference-between--optional-and--kubebuildervalidationoptional, mind giving it a go?

**Review by leelavg — APPROVED** [review]

**Comment by rohan47** [comment]
The changes are tested.

**Pull request merged**
