### PR TITLE
provider: split protobuf related pkgs into a separate go module

### PR DESCRIPTION
**Pull request by leelavg**
pb -> now contains generated proto stubs, interface implementations and client api

existing package paths are updated accordingly, this is to solve huge dep updates (whole of ocs-operator) being pulled when a change is done to proto and corresponding stubs.

### CODE REVIEW

**Comment by leelavg** [comment]
atm client-op doesn't have dependency on ocs-op expect for newly created standalone modules
```
> go mod why github.com/red-hat-storage/ocs-operator/v4
# github.com/red-hat-storage/ocs-operator/v4
(main module does not need package github.com/red-hat-storage/ocs-operator/v4)

> go mod why github.com/red-hat-storage/ocs-operator/v4/services/provider/client
# github.com/red-hat-storage/ocs-operator/v4/services/provider/client
github.com/red-hat-storage/ocs-client-operator/internal/controller
github.com/red-hat-storage/ocs-operator/v4/services/provider/client

> go mod why github.com/red-hat-storage/ocs-operator/v4/services/provider/interfaces
# github.com/red-hat-storage/ocs-operator/v4/services/provider/interfaces
github.com/red-hat-storage/ocs-client-operator/service/status-report
github.com/red-hat-storage/ocs-operator/v4/services/provider/interfaces

> go mod why github.com/red-hat-storage/ocs-operator/v4/services/provider/pb
# github.com/red-hat-storage/ocs-operator/v4/services/provider/pb
github.com/red-hat-storage/ocs-client-operator/internal/controller
github.com/red-hat-storage/ocs-operator/v4/services/provider/client
github.com/red-hat-storage/ocs-operator/v4/services/provider/pb
```

**Comment by leelavg** [comment]
can review only first commit and second is the result of `go mod vendor`

**Comment by leelavg** [comment]
/hold

Checking client-op compilation based on this PR

**Comment by nb-ohad** [comment]
I don't think we should have a package with only the PB. Let have an offline discussion on this

**Comment by leelavg** [comment]
> I don't think we should have a package with only the PB. Let have an offline discussion on this
- updated, pls review.

**Comment by leelavg** [comment]
/unhold

Tested below scenarios:
1. updating the proto and make target regenerates the stubs
2. used this pr as dep in client-op and able to compile the binaries

**Review by nb-ohad — CHANGES_REQUESTED** [review]
I think it makes more sense calling the new package `provider/api` as it contain more then just protobufs

**Comment by leelavg** [comment]
> I think it makes more sense calling the new package `provider/api` as it contain more then just protobufs
- done.

**Pull request merged**
