### PR TITLE
Remove annotation to enable add-capacity for csv

### PR DESCRIPTION
**Pull request by SanjalKatiyar**
Removed a flag which is disabling UI components in Console.
Used to track migration of features from OCP to ODF.
Signed-off-by: SanjalKatiyar <sanjaldhir@gmail.com>

### CODE REVIEW

**Comment by SanjalKatiyar** [comment]
Do not merge right now... waiting for https://github.com/openshift/console/pull/11515 to get closed before merging.
not adding hold tag otherwise CI will not run.

**Comment by SanjalKatiyar** [comment]
@iamniting plz merge this. Thanks.

**Comment by SanjalKatiyar** [comment]
@umangachapagain plz merge this. Thanks.

**Review by umangachapagain — APPROVED** [review]

**Pull request merged**
