### PR TITLE
remove duplicate install scripts

### PR DESCRIPTION
**Pull request by iamniting**
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

### CODE REVIEW

**Comment by malayparida2000** [comment]
I think we can also remove the catalog/sub based things in our repo now as the bundle based installs are much more clearer & achieve all requirements for ocs-operator installation(i.e installing for dev testing & CI). If you agree I can raise a separate PR for that.

**Review by malayparida2000 — APPROVED** [review]
/lgtm

**Comment by iamniting** [comment]
> I think we can also remove the catalog/sub based things in our repo now as the bundle based installs are much more clearer & achieve all requirements for ocs-operator installation(i.e installing for dev testing & CI). If you agree I can raise a separate PR for that.

Lets keep them for now as they are still supported and working.

**Comment by malayparida2000** [comment]
> > I think we can also remove the catalog/sub based things in our repo now as the bundle based installs are much more clearer & achieve all requirements for ocs-operator installation(i.e installing for dev testing & CI). If you agree I can raise a separate PR for that.
> 
> Lets keep them for now as they are still supported and working.

Actually they are broken right now, with all the recent overhaul related to all the csvs we had the readme file is now broken, I also have no idea which subs to create in which order to get it working. So we either figure out the correct way & correct the readme or remove it all together.

**Pull request merged**
