### PR TITLE
Bug 2273923:[release-4.15] [MCG] add support for deploying NooBaa operator SCC along with Rook SCCs

### PR DESCRIPTION
**Pull request by tangledbytes**
This is a backport PR. Original PR - https://github.com/red-hat-storage/ocs-operator/pull/2655

This PR adds support for provisioning SCC for NooBaa operator alongside the Rook Operator. NooBaa operator added this SCC due to the IBM security requirements raised a few months ago.

Corresponding BZ created for NooBaa/MCG - https://bugzilla.redhat.com/show_bug.cgi?id=2273923

### CODE REVIEW

**Review by iamniting — APPROVED** [review]

**Comment by iamniting** [comment]
Hi @tangledbytes Can you please create a clone of the BZs in the ocs-operator, We do need acks and all to get the BZ in.

**Comment by nimrod-becker** [comment]
The linked BZ seems private and without acks due to access issues we are all having with Bugzilla.
The BZ is acked, do we really need another clone just for the ocs-op component ?

**Comment by iamniting** [comment]
> The linked BZ seems private and without acks due to access issues we are all having with Bugzilla. The BZ is acked, do we really need another clone just for the ocs-op component ?

I am not able to see the acks, @agarwal-mudit shall I go ahead and add the labels manually?

**Comment by agarwal-mudit** [comment]
Ideally we should have a separate BZ for each component but I am ok with exception this time. 
@nimrod-becker we decided to move this BZ to 4.15.4, so this can be merged next week now

**Comment by tangledbytes** [comment]
@iamniting can we get this PR merged?

**Pull request merged**
