### PR TITLE
Add 'runbook_url' link to alerts' annotation

### PR DESCRIPTION
**Pull request by aruniiird**
Adding 'runbook_url' link to following alerts,

CephMgrIsAbsent
CephMgrIsMissingReplicas
CephMdsMissingReplicas
CephMonQuorumAtRisk
CephMonQuorumLost
CephMonHighNumberOfLeaderChanges
CephNodeDown
CephOSDCriticallyFull

ObcQuotaObjectsAlert
ObcQuotaBytesExhausedAlert
ObcQuotaObjectsExhausedAlert
ClusterObjectStoreState

### CODE REVIEW

**Comment by aruniiird** [comment]
@jmolmo , @umangachapagain , please take a look.

**Review by jmolmo — APPROVED** [review]

**Review by umangachapagain — APPROVED** [review]

**Comment by aruniiird** [comment]
golangci-lint test is not a mandatory (we never touch any go file in this PR) and all the required tests are passed.
If we see the error message, above, it says we require TWO approving reviews (got ONE and need one more)
@jmolmo , can you please take a look?

**Review by jmolmo — APPROVED** [review]

**Review by umangachapagain — COMMENTED** [review]
We can not skip github-action tests and since it's a month old PR, we can not re-run the tests.
As a workaround, please make some change to the commit (to change it's commit id) and force push the PR. That should allow us to re-run all tests and merge.

**Comment by aruniiird** [comment]
Rebased and force pushed the changes to trigger testing

**Comment by agarwal-mudit** [comment]
@umangachapagain can we add /lgtm back

**Review by umangachapagain — APPROVED** [review]

**Pull request merged**
