### PR TITLE
Added 'namespace' tag to queries

### PR DESCRIPTION
**Pull request by aruniiird**
This will allow the results to be grouped by namespace and not dependent on any particular one.

### CODE REVIEW

**Review by umangachapagain — COMMENTED** [review]
Have you verified if the results of both the queries is the same?

**Comment by aruniiird** [comment]
> Have you verified if the results of both the queries is the same?

Yes verified each query (even the alerts, but could not fire each and every alerts, so tested the query without the condition. ie for eg:  'SOME-QUERY' > 0.75, just tested the 'SOME-QUERY' part to see it is giving appropriate results or not)

**Comment by aruniiird** [comment]
Another related change added through PR:https://github.com/red-hat-storage/ocs-operator/pull/2008
@umangachapagain ^

**Comment by aruniiird** [comment]
Good to go, let me know if anything to be changed

**Review by umangachapagain — APPROVED** [review]

**Pull request merged**
