### PR TITLE
Add default TSCs if not present to ensure even distribution of OSDs

### PR DESCRIPTION
**Pull request by malayparida2000**
When parts of the placement spec, such as tolerations or node affinity, are defined, the ocs-operator stops applying default placement specs, including TSCs. The osd distribution may become potentially uneven in absence of the TSC. Always adding default TSCs ensures consistent and balanced OSD placement across nodes.

### CODE REVIEW

**Comment by malayparida2000** [comment]
Ref-https://issues.redhat.com/browse/DFBUGS-637

**Comment by malayparida2000** [comment]
Test storagecluster, One deviceset with placement, another deviceset without placement.
```
cat <<EOF | oc create -f -
apiVersion: [ocs.openshift.io/v1](http://ocs.openshift.io/v1)
kind: StorageCluster
metadata:
  ownerReferences:
  - apiVersion: v1
    kind: StorageSystem
    name: ocs-storagecluster-storagesystem
    uid: ocs-storagecluster-storagesystem
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  storageDeviceSets:
    - name: without-placement
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "1Ti"
          storageClassName: gp3-csi
          volumeMode: Block
      count: 1
      replica: 3
      portable: true
    - name: with-placement
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "1Ti"
          storageClassName: gp3-csi
          volumeMode: Block
      count: 1
      replica: 3
      portable: true
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: [topology.kubernetes.io/region](http://topology.kubernetes.io/region)
                operator: In
                values:
                - us-east-1
EOF
```
Without FIx-Deviceset placement on cephCluster CR
```
~ $ oc get cephcluster ocs-storagecluster-cephcluster -o yaml | yq '.spec.storage.storageClassDeviceSets[] | {"name": .name, "placement": .placement, "preparePlacement": .preparePlacement}' -P | sed 's/^/  /' | sed 's/^  name/- name/' 
- name: without-placement-0
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [cluster.ocs.openshift.io/openshift-storage](http://cluster.ocs.openshift.io/openshift-storage)
                operator: Exists
    tolerations:
      - effect: NoSchedule
        key: [node.ocs.openshift.io/storage](http://node.ocs.openshift.io/storage)
        operator: Equal
        value: "true"
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
  preparePlacement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [cluster.ocs.openshift.io/openshift-storage](http://cluster.ocs.openshift.io/openshift-storage)
                operator: Exists
    tolerations:
      - effect: NoSchedule
        key: [node.ocs.openshift.io/storage](http://node.ocs.openshift.io/storage)
        operator: Equal
        value: "true"
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
- name: without-placement-1
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [cluster.ocs.openshift.io/openshift-storage](http://cluster.ocs.openshift.io/openshift-storage)
                operator: Exists
    tolerations:
      - effect: NoSchedule
        key: [node.ocs.openshift.io/storage](http://node.ocs.openshift.io/storage)
        operator: Equal
        value: "true"
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
  preparePlacement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [cluster.ocs.openshift.io/openshift-storage](http://cluster.ocs.openshift.io/openshift-storage)
                operator: Exists
    tolerations:
      - effect: NoSchedule
        key: [node.ocs.openshift.io/storage](http://node.ocs.openshift.io/storage)
        operator: Equal
        value: "true"
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
- name: without-placement-2
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [cluster.ocs.openshift.io/openshift-storage](http://cluster.ocs.openshift.io/openshift-storage)
                operator: Exists
    tolerations:
      - effect: NoSchedule
        key: [node.ocs.openshift.io/storage](http://node.ocs.openshift.io/storage)
        operator: Equal
        value: "true"
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
  preparePlacement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [cluster.ocs.openshift.io/openshift-storage](http://cluster.ocs.openshift.io/openshift-storage)
                operator: Exists
    tolerations:
      - effect: NoSchedule
        key: [node.ocs.openshift.io/storage](http://node.ocs.openshift.io/storage)
        operator: Equal
        value: "true"
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
- name: with-placement-0
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [topology.kubernetes.io/region](http://topology.kubernetes.io/region)
                operator: In
                values:
                  - us-east-1
  preparePlacement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [topology.kubernetes.io/region](http://topology.kubernetes.io/region)
                operator: In
                values:
                  - us-east-1
- name: with-placement-1
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [topology.kubernetes.io/region](http://topology.kubernetes.io/region)
                operator: In
                values:
                  - us-east-1
  preparePlacement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [topology.kubernetes.io/region](http://topology.kubernetes.io/region)
                operator: In
                values:
                  - us-east-1
- name: with-placement-2
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [topology.kubernetes.io/region](http://topology.kubernetes.io/region)
                operator: In
                values:
                  - us-east-1
  preparePlacement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [topology.kubernetes.io/region](http://topology.kubernetes.io/region)
                operator: In
                values:
                  - us-east-1
```

With Fix-DeviceSet Placement on CephCluster CR
```
~ $ oc get cephcluster ocs-storagecluster-cephcluster -o yaml | yq '.spec.storage.storageClassDeviceSets[] | {"name": .name, "placement": .placement, "preparePlacement": .preparePlacement}' -P | sed 's/^/  /' | sed 's/^  name/- name/'
- name: without-placement-0
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [cluster.ocs.openshift.io/openshift-storage](http://cluster.ocs.openshift.io/openshift-storage)
                operator: Exists
    tolerations:
      - effect: NoSchedule
        key: [node.ocs.openshift.io/storage](http://node.ocs.openshift.io/storage)
        operator: Equal
        value: "true"
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
  preparePlacement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [cluster.ocs.openshift.io/openshift-storage](http://cluster.ocs.openshift.io/openshift-storage)
                operator: Exists
    tolerations:
      - effect: NoSchedule
        key: [node.ocs.openshift.io/storage](http://node.ocs.openshift.io/storage)
        operator: Equal
        value: "true"
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
- name: without-placement-1
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [cluster.ocs.openshift.io/openshift-storage](http://cluster.ocs.openshift.io/openshift-storage)
                operator: Exists
    tolerations:
      - effect: NoSchedule
        key: [node.ocs.openshift.io/storage](http://node.ocs.openshift.io/storage)
        operator: Equal
        value: "true"
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
  preparePlacement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [cluster.ocs.openshift.io/openshift-storage](http://cluster.ocs.openshift.io/openshift-storage)
                operator: Exists
    tolerations:
      - effect: NoSchedule
        key: [node.ocs.openshift.io/storage](http://node.ocs.openshift.io/storage)
        operator: Equal
        value: "true"
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
- name: without-placement-2
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [cluster.ocs.openshift.io/openshift-storage](http://cluster.ocs.openshift.io/openshift-storage)
                operator: Exists
    tolerations:
      - effect: NoSchedule
        key: [node.ocs.openshift.io/storage](http://node.ocs.openshift.io/storage)
        operator: Equal
        value: "true"
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
  preparePlacement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [cluster.ocs.openshift.io/openshift-storage](http://cluster.ocs.openshift.io/openshift-storage)
                operator: Exists
    tolerations:
      - effect: NoSchedule
        key: [node.ocs.openshift.io/storage](http://node.ocs.openshift.io/storage)
        operator: Equal
        value: "true"
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
- name: with-placement-0
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [topology.kubernetes.io/region](http://topology.kubernetes.io/region)
                operator: In
                values:
                  - us-east-1
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
  preparePlacement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [topology.kubernetes.io/region](http://topology.kubernetes.io/region)
                operator: In
                values:
                  - us-east-1
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
- name: with-placement-1
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [topology.kubernetes.io/region](http://topology.kubernetes.io/region)
                operator: In
                values:
                  - us-east-1
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
  preparePlacement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [topology.kubernetes.io/region](http://topology.kubernetes.io/region)
                operator: In
                values:
                  - us-east-1
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
                - rook-ceph-osd-prepare
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
- name: with-placement-2
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [topology.kubernetes.io/region](http://topology.kubernetes.io/region)
                operator: In
                values:
                  - us-east-1
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [topology.rook.io/rack](http://topology.rook.io/rack)
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - rook-ceph-osd
        maxSkew: 1
        topologyKey: [kubernetes.io/hostname](http://kubernetes.io/hostname)
        whenUnsatisfiable: ScheduleAnyway
  preparePlacement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: [topology.kubernetes.io/region](http://topology.kubernetes.io/region)
                operator: In
                values:
                  - us-east-1
    topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
```

**Comment by malayparida2000** [comment]
As seen in testing TSCs are getting applied as expected, Removing hold
/unhold

**Review by iamniting — APPROVED** [review]

**Pull request merged**
