### PR TITLE
update noobaa version that is compatible with rook 1.13.1

### PR DESCRIPTION
**Pull request by v-harihar**
update noobaa version that is compatible with rook 1.13.1

### CODE REVIEW

**Comment by v-harihar** [comment]
@umangachapagain Please review

**Comment by v-harihar** [comment]
@liranmauda Please take a look

**Comment by malayparida2000** [comment]
Changes look good, @iamniting PTAL

**Review by iamniting — CHANGES_REQUESTED** [review]
pls update api go.mod as well.

**Review by iamniting — CHANGES_REQUESTED** [review]
pls add `make gen-latest-csv` changes as well.

**Review by iamniting — APPROVED** [review]

**Review by umangachapagain — APPROVED** [review]

**Pull request merged**
