### PR TITLE
Finalizing migration of OB/OBC CRDs

### PR DESCRIPTION
**Pull request by jarrpa**
This PR removes all dependencies on the noobaa-operator bundle, CSV, and CRDs. This fully decouples the ocs-operator and noobaa-operator bundles, allowing for greater flexibility in the deployment of both components.

### CODE REVIEW

**Comment by jarrpa** [comment]
Putting this on hold to allow for further discussions. If no one comes up with anything clever by the end of the week I will release it and let it merge. :relaxed: 

/hold

**Comment by BlaineEXE** [comment]
/lgtm

I don't see anything concerning here, though I'm not as familiar with ocs-operator as I'd hope.

From the Rook angle, I wonder if this means we can stop including the OB/OBC CRDs in our CSV. I'll discuss with @travisn and crew in Rook huddle.

**Review by BlaineEXE — APPROVED** [review]

**Comment by malayparida2000** [comment]
@jarrpa Can you look at the bundle e2e aws test. it seems like a genuine failure. The error is coming from here https://github.com/red-hat-storage/ocs-operator/blob/e6914fb2fcc09a17d03cec1d3ef0411c708e32cb/pkg/deploy-manager/storagecluster.go#L290 , where the storagecluster is not getting to the available condition.

**Review by iamniting — APPROVED** [review]
/hold cancel
/lgtm

**Pull request merged**
