### PR TITLE
Changed alerts queries to support multicluster mode

### PR DESCRIPTION
**Pull request by aruniiird**
Added needed changes for alerts queries to support multicluster mode

### CODE REVIEW

**Comment by aruniiird** [comment]
Just an FYI
Rules/Alerts under name: `ceph-daemon-performance-alerts.rules`, don't have `managedBy` label

**Comment by aruniiird** [comment]
Added `managedBy` label to alert queries to support multicluster scenario.
@umangachapagain , please take a look

**Review by umangachapagain — COMMENTED** [review]
> Just an FYI Rules/Alerts under name: `ceph-daemon-performance-alerts.rules`, don't have `managedBy` label
>
All metrics should have that label by default. @aruniiird  Do you see any issues with the query?
I see many other queries that aren't grouped by `managedBy` label. Is it not needed for those queries? Like for standardized metrics queries.

**Comment by umangachapagain** [comment]
@aruniiird Looks like ceph metrics are not working correctly. We inject "managedBy" labels in them.
Let's create an issue for it an investigate.

Kube metrics will not have the labels. But, that shouldn't matter. We should be able to use our labels in the queries.
Let's create another issue and track that as well.

Merging these changes.
Thank you.

**Review by umangachapagain — APPROVED** [review]

**Pull request merged**
