### PR TITLE
Bug 2186443:[release-4.12] remove storageClassClaim and add new storageClassRequest CR

### PR DESCRIPTION
**Pull request by subhamkrai**
see individual commits

### CODE REVIEW

**Comment by subhamkrai** [comment]
@iamniting @Madhu-1 @nb-ohad @rewantsoni ^^

**Comment by subhamkrai** [comment]
golangci lint errors are not coming from my changes so not making part of this pr since it is already a big pr. Thanks

**Comment by iamniting** [comment]
@subhamkrai Can you look at the failures?

**Comment by Madhu-1** [comment]
@subhamkrai can you please check @iamniting comment?

**Comment by subhamkrai** [comment]
@iamniting ptal

**Review by iamniting — APPROVED** [review]

**Pull request merged**
