### PR TITLE
Decreasing the timeout of 'ODF_standardized_metrics.rules' group to 30s

### PR DESCRIPTION
**Pull request by aruniiird**
In order to make the 'odf_system_iops_total_bytes' recording rule to
collect more granular metric data points, we are decreasing the
recording rule group's time interval to 30s (where default is 1m).

Signed-off-by: Arun Kumar Mohan <amohan@redhat.com>

### CODE REVIEW

**Review by umangachapagain — CHANGES_REQUESTED** [review]
I believe you also need to add the generated changes.

**Review by jarrpa — APPROVED** [review]
/lgtm

**Pull request merged**
