### PR TITLE
rename storageclassclaim to storageclaim in gRPC methods

### PR DESCRIPTION
**Pull request by leelavg**
storageclassclaim API is owned by ocs-client and it was recently renamed to storageclaim, this PR propagates those changes internally used in gRPC methods.

no older client can not connect to the updated provider w/ this change however the client which doesn't have the rename of the API changes is implicitly not compatible w/ the underlying storage provided by storageclaim, as such the storage will be migrated as part of different effort and this PR is mutually exclusive to it.

### CODE REVIEW

**Comment by nb-ohad** [comment]
LGTM

**Comment by leelavg** [comment]
needs an override due to CI not able to create OCP cluster
```
 INFO[2024-04-16T14:55:09Z] Logs for container test in pod ocs-operator-bundle-e2e-aws-ipi-conf: 
INFO[2024-04-16T14:55:09Z] Installing from release registry.build05.ci.openshift.org/ci-op-g7qdg70k/release@sha256:787177af35220d3e31a557eea247c791a83139528912bc9c4fed57ae74d32418
/bin/bash: line 19: /var/run/secrets/ci.openshift.io/cluster-profile/ssh-publickey: No such file or directory
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:84","func":"k8s.io/test-infra/prow/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2024-04-16T14:55:08Z"}
error: failed to execute wrapped command: exit status 1 
INFO[2024-04-16T14:55:10Z] Step ocs-operator-bundle-e2e-aws-ipi-conf failed after 7s. 
INFO[2024-04-16T14:55:10Z] Step phase pre failed after 7s.  
```
and the changes in this PR aren't testable in CI, however static analysis is passed.

**Comment by leelavg** [comment]
rebased.

**Comment by leelavg** [comment]
CI passed w/ a workaround
```
PVC Creation rbd create pvc and verify bound status
/go/src/github.com/red-hat-storage/ocs-operator/functests/ocs/pvc_creation_test.go:43
  STEP: Creating PVC @ 04/16/24 17:00:25.119
  STEP: Deleting PVC @ 04/16/24 17:00:26.256
• [1.272 seconds]
------------------------------
P [PENDING]
Cluster upgrade ocs upgrade cluster and verify deployment status
/go/src/github.com/red-hat-storage/ocs-operator/functests/ocs/cluster_upgrade_test.go:39
------------------------------
[AfterSuite] 
/go/src/github.com/red-hat-storage/ocs-operator/functests/ocs/ocs_test.go:20
  ------------------------------
  AfterTestSuite: deleting Namespace ocs-functest
[AfterSuite] PASSED [20.138 seconds]
------------------------------
Ran 4 of 5 Specs in 1169.113 seconds
SUCCESS! -- 4 Passed | 0 Failed | 1 Pending | 0 Skipped
PASS```

we need to push updated u/s ocs-client-op bundle.

**Pull request merged**
