### PR TITLE
Bug 2188228: [release-4.12] Namespace agnostic metric exporter code

### PR DESCRIPTION
**Pull request by aruniiird**
Backport PR for release-4.12
Had to pick @weirdwiz 's changes for 'Add new metric for monitoring blocklisted RBD clients' PR#1937 as well to resolve conflicts.

### CODE REVIEW

**Review by umangachapagain — CHANGES_REQUESTED** [review]
No need to cherry-pick fixes for things that didn't exist it 4.12.
Cherry-pick fixes only if issue existed in 4.12 or add custom fix on 4.12.

**Comment by aruniiird** [comment]
> No need to cherry-pick fixes for things that didn't exist it 4.12. Cherry-pick fixes only if issue existed in 4.12 or add custom fix on 4.12.

@umangachapagain , then there is nothing to cherry-pick, because all the changes where done were on top of @weirdwiz 's refactor code changes. Then, as you said, it will totally be a new/custom fix for release-4.12

**Comment by aruniiird** [comment]
After a check on 4.12 branch, we don't require any changes in this PR as all the issues were related to the refactor.
If we are not backporting the refactor code, we don't require any fix for release-4.12.
We can close this PR...

**Comment by aruniiird** [comment]
Closing the PR, as the change/backport is not needed for 4.12 release branch

**Pull request closed without merging**
