### PR TITLE
Notify if KMS connection to the server is lost

### PR DESCRIPTION
**Pull request by rexagod**
Let users know if the connection to the KMS server was lost by including
`KMSServerConnectionStatus` in the `StorageClusterSpec`. This will add a
`KMSServerConnectionStatus` field consisting of the following information:
  - `KMSServerAddress`: The address of the KMS server.
  - `KMSServerConnectionError`: An error message that's thrown when the
    connection is lost.

### CODE REVIEW

**Comment by rexagod** [comment]
Not sure why this is failing, I've already pushed the artifacts generated from `make update-generated`.

**Comment by rexagod** [comment]
Maybe this is a CI issue?

https://prow.ci.openshift.org/?repo=red-hat-storage%2Focs-operator&state=failure

**Comment by rexagod** [comment]
@jarrpa Can you PTAL at the CI logs?

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/red-hat-storage_ocs-operator/1419/pull-ci-red-hat-storage-ocs-operator-main-red-hat-storage-ocs-ci-e2e-aws/1488267652865462272#1:build-log.txt%3A259

**Review by umangachapagain — CHANGES_REQUESTED** [review]
Please add a test to ensure that required condition is updated.

Also, on commit message you don't need to add tags like  `[RFE]` or `[Generated]`. Instead just explain what each commit does.

**Comment by rexagod** [comment]
Bugzilla link: https://bugzilla.redhat.com/show_bug.cgi?id=1944687

**Comment by umangachapagain** [comment]
@rexagod On your 2nd commit `update metadata` the commit hash you mentioned is referenced from your private branch.
Remove it. `update metadata` is enough.

**Review by umangachapagain — APPROVED** [review]

**Pull request merged**
