### PR TITLE
Bug 1984735: [release-4.8] Release 4.8 fix external resources updation

### PR DESCRIPTION
**Pull request by aruniiird**
Backport from PR#1286, which updates the external cluster resources according JSON input changes.

### CODE REVIEW

**Comment by jarrpa** [comment]
@aruniiird you should at least include the KMS unit test fix commit form the original PR. It will solve a lot of problems going forward.

**Comment by aruniiird** [comment]
> @aruniiird you should at least include the KMS unit test fix commit form the original PR. It will solve a lot of problems going forward.

Was not sure, whether to add the tests part into release-4.8 branch. Added it
@jarrpa please take a look...

**Comment by agarwal-mudit** [comment]
@aruniiird This is part of which BZ? We should have an approved BZ for z-stream releases

**Comment by aruniiird** [comment]
> @aruniiird This is part of which BZ? We should have an approved BZ for z-stream releases

This is part of BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1984735

**Comment by agarwal-mudit** [comment]
> > @aruniiird This is part of which BZ? We should have an approved BZ for z-stream releases
> 
> This is part of BZ:
> https://bugzilla.redhat.com/show_bug.cgi?id=1984735

@aruniiird @jarrpa Do we need this fix for 4.8.z, is it that important? I don't think it affects any functionality.

**Comment by jarrpa** [comment]
Oops, forgot to respond to this. Doesn't look like we need this as a backport.

**Pull request closed without merging**
