### PR TITLE
Fix storagecluster version in odfinfoconfig unit test

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Update storagcluster version in odfinfoconfig test to 4.17

### CODE REVIEW

**Review by iamniting — APPROVED** [review]

**Review by raaizik — APPROVED** [review]

**Comment by raaizik** [comment]
Pasting relevant [comment](https://github.com/red-hat-storage/ocs-operator/pull/2440#discussion_r1606657764). I tend to agree as mentioned in my first comment this var's value is better off as a dummy.

**Comment by malayparida2000** [comment]
The e2e is failing due to ocs-client-operator installation failing

**Comment by Nikhil-Ladha** [comment]
> Pasting relevant [comment](https://github.com/red-hat-storage/ocs-operator/pull/2440#discussion_r1606657764). @Nikhil-Ladha, I tend to agree as as mentioned in my first comment this data is better off as a dummy.

Technically, it is not a dummy value. But, a hardcoded value that would change in each release.

**Comment by raaizik** [comment]
> > Pasting relevant [comment](https://github.com/red-hat-storage/ocs-operator/pull/2440#discussion_r1606657764). @Nikhil-Ladha, I tend to agree as as mentioned in my first comment this data is better off as a dummy.
> 
> Technically, it is not a dummy value. But, a hardcoded value that would change in each release.

But IMO this type of data should be treated as a mock in tests and not in a way that stores its real value.

**Comment by Nikhil-Ladha** [comment]
> > > Pasting relevant [comment](https://github.com/red-hat-storage/ocs-operator/pull/2440#discussion_r1606657764). @Nikhil-Ladha, I tend to agree as as mentioned in my first comment this data is better off as a dummy.
> > 
> > 
> > Technically, it is not a dummy value. But, a hardcoded value that would change in each release.
> 
> But IMO this type of data should be treated as a mock in tests and not in a way that stores its real value.

It should be, but in the part of code that this test is testing out, we can't set version to a mock value, since it is comparing the value with an actual storagecluster that is created in the test env.

**Pull request merged**
