### PR TITLE
Update rook api and image to latest version and also updated the default service account in toolbox pod

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
- Updated rook api, image to latest version
- We are now using latest downstream rook image, i.e, red-hat-storage/rook since we are now actively maintaining the downstream fork and there are some downstream only changes that is required for the ocs-operator to run properly.
- Updated the code to use VolumeClaimTemplate instead of PersistentVolumeClaim
- Added default service account for toolbox pod, as the rook scc is now updated and the default service account is removed.

### CODE REVIEW

**Review by iamniting — CHANGES_REQUESTED** [review]
@Nikhil-Ladha Can you pls remove the struct changes for now, The CI is failing because we don't have go.work file in the CI and we can not create it due to DS build tools.

**Review by iamniting — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
We would probably need to update the rook image as well, will do it on Monday once we have the Travis's PR merged as well.
https://github.com/rook/rook/pull/13936

**Comment by parth-gr** [comment]
@Nikhil-Ladha we dont need the upstream PR, but we have a separate pr for downstream https://github.com/red-hat-storage/ocs-operator/pull/2511
And that PR is depending on this PR to get merged first, so to update the CI rook image with latest

So if this is all done can we merge it

**Review by parth-gr — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
PR is all set, we are having issues with CI that's the reason the PR is not merged.

**Comment by iamniting** [comment]
@Nikhil-Ladha Can you pls take a look at the CI failure? I just restarted it. It will take half an hour to deploy the setup. pls do keep an eye on it.

**Review by iamniting — APPROVED** [review]

**Comment by iamniting** [comment]
/override ci/prow/ci-bundle-ocs-operator-bundle

The CI is passed once, no need to run it again

**Pull request merged**
