### PR TITLE
Bug 2273670:[release-4.16] [MCG] add support for deploying NooBaa operator SCC along with Rook SCCs

### PR DESCRIPTION
**Pull request by tangledbytes**
This is a backport PR. Original PR - https://github.com/red-hat-storage/ocs-operator/pull/2655

This PR adds support for provisioning SCC for NooBaa operator alongside the Rook Operator. NooBaa operator added this SCC due to the IBM security requirements raised a few months ago.

Corresponding BZ created for NooBaa/MCG - https://bugzilla.redhat.com/show_bug.cgi?id=2273670

### CODE REVIEW

**Review by iamniting — APPROVED** [review]

**Comment by iamniting** [comment]
Hi @tangledbytes Can you please create a clone of the BZs in the ocs-operator, We do need acks and all to get the BZ in.

**Comment by tangledbytes** [comment]
@iamniting can we get this PR merged?

**Pull request merged**
